### ISSUE TITLE
Todo do ToDo

### ISSUE THREAD

**Issue by elloramir** [passjoao/ToDo#1]

**Comment by elloramir** [comment]
- [ ] login
- [ ] insert new task
- [ ] update created task
- [ ] remove created task
